language: scala

jdk: oraclejdk8

scala:
  - 2.12.8

services:
  - postgresql

before_script:
  - psql -c 'create database playdb;' -U postgres

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)